Regex pipeline introduction
PKM-er/Pkmer-Docs pull request #110
Opened 2023-05-25 05:21 UTC by Geralt-TYH

新增regex pipline插件介绍

2023-05-25 09:24 UTC, windily-cloud commented on Regex Pipeline.md
文章名称使用插件id，在manifest.json里可以找到。此举是为了在插件浏览界面跳到我们的插件文档。

2023-05-25 09:25 UTC, windily-cloud commented on Regex Pipeline.md
> +> - 插件描述：
最好来个插件描述，和yaml中一致，此举是为了更高的seo

2023-05-25 09:26 UTC, windily-cloud requested changes
麻烦修改一下：
1. 文件名称应使用插件id
2. 增加插件描述

2023-05-26 05:19 UTC, Geralt-TYH commented on Regex Pipeline.md
> +> - 插件描述：
已增加

2023-05-26 07:24 UTC, merged