增加Zotero Style、
PKM-er/Pkmer-Docs pull request #319
Opened 2023-07-26 01:05 UTC by MuiseDestiny

2023-07-27 13:05 UTC, windily-cloud commented
写完我再合哈，现在先看大佬表演😊

2023-07-30 06:13 UTC, juestchaos commented
给大佬点赞，大佬你准备更新多少讲？如果有预期，我们商量下，是否先放出来一部分

2023-07-30 07:52 UTC, MuiseDestiny commented
> 给大佬点赞，大佬你准备更新多少讲？如果有预期，我们商量下，是否先放出来一部分

我先更一个style后面慢慢写。写的比较随意，需要优化优化~

2023-08-08 01:08 UTC, windily-cloud commented on 50-教程/Zotero/第三讲.md
> +# 第三讲
这个文件是不是没必要的

2023-08-08 01:09 UTC, windily-cloud commented on 11-Zotero/Zotero插件/Zotero Style.md
> +一款高度自由化、高度自定义Zotero扩展功能的插件。
这里几乎没有zotero style插件的介绍，我认为有必要介绍这么优秀插件的主要功能，就像茉莉花插件的那篇。而且这个pr并没有yaml，格式得注意一下

2023-08-08 01:15 UTC, windily-cloud requested changes

2023-08-08 01:15 UTC, windily-cloud commented on 11-Zotero/Zotero插件/Zotero Style.md
> +1. 打开es[官网](https://www.easyscholar.cc/)
这里是一张付费截图，这样pkmer会有广告嫌疑，影响观感。最好的办法可能提一句easyScholar是付费的，不要出现任何需要跳转的付费链接，开源免费的可以没有这个顾虑。

2023-08-08 01:15 UTC, windily-cloud commented on 11-Zotero/Zotero插件/Zotero Style.md
> +
整体而言，并没有介绍zotero style插件，而仅仅是常见问题的汇总，对于不熟悉这个插件的人可能很迷惑。既然标题是zotero style，建议还是详细介绍下该插件的功能及使用场景。

2023-08-31 14:21 UTC, closed without merging