协助补充 ZotLit 资料：增加 Obsidian ZotLit 的使用技巧演示
PKM-er/Pkmer-Docs pull request #511
Opened 2023-11-14 13:14 UTC by alephpiece

协助A大和社区补充 ZotLit 资料，增加简单的演示。

这个演示里面包括：
- 工作流需求
- 插件卡片
- 基本功能演示动图
- 个人配置分享

不知道这个稿子是否合适？

2023-11-14 15:34 UTC, alephpiece commented
这周我想把另外一篇演示 ZotLit 模板的也加上，但是还需要改改，之前写的感觉不太清楚

2023-11-16 00:28 UTC, windily-cloud commented
> 这周我想把另外一篇演示 ZotLit 模板的也加上，但是还需要改改，之前写的感觉不太清楚

好的，辛苦了，那我暂时不合并了，等你写完

2023-11-16 11:41 UTC, alephpiece commented
谢谢大佬 :)

2023-11-18 10:52 UTC, alephpiece commented
总共两篇文章都加上了 :) 请大佬检查

2023-11-18 11:49 UTC, windily-cloud commented on 10-Obsidian/Obsidian使用技巧/ZotLit带来的文献引用流畅体验.md
> +```Eta
eta没有高亮代码块，可以去掉

2023-11-18 11:50 UTC, windily-cloud commented on 10-Obsidian/Obsidian使用技巧/ZotLit带来的文献引用流畅体验.md
> +```Text
text类代码块可以不标，而且这前后不一致

2023-11-18 11:51 UTC, windily-cloud requested changes
其它的就很好，感谢贡献。

2023-11-18 11:54 UTC, alephpiece commented on 10-Obsidian/Obsidian使用技巧/ZotLit带来的文献引用流畅体验.md
> +```Eta
好的，我把两个文件里的 `Eta` 都删掉了

2023-11-18 11:54 UTC, alephpiece commented on 10-Obsidian/Obsidian使用技巧/ZotLit带来的文献引用流畅体验.md
> +```Text
这个我也删掉了

2023-11-18 15:04 UTC, merged